test

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -1,34 +1,89 @@
-# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
-# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
-
-name: Maven Package
+name: Deploy Dev
 
 on:
   push:
-    branches: [main]
-  release:
-    types: [created]
+    branches: [test]
+
+env:
+  ACCOUNT_ID: CVETDEV.test
+  ACCOUNT_USERNAME: cvetdev_admin
+  ACCOUNT_PASSWORD: cvetdev_admin
+  CLIENT_ID: CVETDEV
+  CLIENT_SECRET: 9c3acda0-5623-4836-b738-5dc8264d8e32
+  BRANCH: test
+  PLUGIN_VERSION: "1.0.1"
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          ref: ${{env.BRANCH}}
 
-    steps:             
-    - name: Build with Maven
-      if: github.ref == 'refs/heads/main'  # Only deploy on pushes to main branch
-      run: |
-       echo ${{ github.workspace }}
-       mvn -B package --file ../pom.xml
+      - name: Run build plugin jar
+        working-directory: covetrus project/cvet
+        run: |
+          mvn versions:set -DnewVersion=${{env.PLUGIN_VERSION}} -f pom.xml --no-transfer-progress
+          mvn clean package -Drubix.osgi.symbolic.name=${{env.ACCOUNT_ID}}.base -DskipTests --no-transfer-progress
 
-    - name: Publish to GitHub Packages Apache Maven
-      run: |
-       chmod +x  ./deployment/retailer1/rubix-install.sh
-       ./deployment/retailer1/rubix-install.sh
-      env:
-        API_HOST: ${{ secrets.DEV_API_HOST }}
-        DEV_ACCOUNT: ${{ vars.DEV_ACCOUNT }}
-        GITHUB_TOKEN: ${{ github.token }}
+      - name: Deploy
+        working-directory: "covetrus project/cvet"
+        shell: /bin/bash -xe {0}
+        run: |
+          echo -e "\nDEPLOYING\n"
+          VERSION="${{env.PLUGIN_VERSION}}"
+          cp $(find ./target -type f -name 'rubix-plugin-fran*.jar') ./rubix-plugin-fran-${VERSION}.jar
+          echo "VERSION: ${VERSION}"
+          BEARER=$(curl -sX POST "https://cvetdev.sandbox.api.fluentretail.com/oauth/token?username=$ACCOUNT_USERNAME&password=$ACCOUNT_PASSWORD&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=password" | jq -r '.access_token')
+          OUTPUT=$(curl -sX POST \
+              -F "file=@./rubix-plugin-fran-${VERSION}.jar" \
+              -H "Authorization: Bearer ${BEARER}" \
+              -H "fluent.account: FRANCESCASDEV" \
+              -H "Content-Type: multipart/form-data" \
+              "https://cvetdev.sandbox.api.fluentretail.com:443/orchestration/rest/v1/plugin/upload")
+
+          STATUS=$(echo ${OUTPUT} | jq -r '.status')
+          if [[ ${STATUS} == 200 ]]; then
+              echo "Deploy successful"
+              echo ${OUTPUT}
+          else
+              echo "Deploy failed"
+              echo ${OUTPUT}
+              exit 1
+          fi
+
+      - name: Install
+        working-directory: covetrus project/cvet
+        run: |
+          echo -e "\nINSTALLING\n"
+          VERSION="${{env.PLUGIN_VERSION}}"
+          BEARER=$(curl -sX POST "https://cvetdev.sandbox.api.fluentretail.com/oauth/token?username=$ACCOUNT_USERNAME&password=$ACCOUNT_PASSWORD&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=password" | jq -r '.access_token')
+          curl -sX POST \
+              -H "Authorization: Bearer ${BEARER}" \
+              -H "fluent.account: FRANCESCASDEV" \
+              -H "Content-Type: application/json" \
+              --data "{\"accountId\":\"FRANCESCASDEV\",\"bundleName\":\"FRANCESCASDEV.base::${VERSION}\"}" \
+              "https://francescasdev.sandbox.api.fluentretail.com:443/orchestration/rest/v1/plugin/install"
+
+      - name: Status
+        working-directory: covetrus project/cvet
+        run: |
+          echo -e "\nSTATUS\n"
+          VERSION="${{env.PLUGIN_VERSION}}"
+          BEARER=$(curl -sX POST "https://cvetdev.sandbox.api.fluentretail.com/oauth/token?username=$ACCOUNT_USERNAME&password=$ACCOUNT_PASSWORD&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=password" | jq -r '.access_token')
+          OUTPUT=$(curl -sX GET \
+              -H "Authorization: Bearer ${BEARER}" \
+              -H "fluent.account: FRANCESCASDEV" \
+              -H "Content-Type: application/json" \
+              "https://francescasdev.sandbox.api.fluentretail.com:443/orchestration/rest/v1/plugin/FRANCESCASDEV.base::${VERSION}/status")
+          STATUS=$(echo ${OUTPUT} | jq -r '.bundleStatus')
+          if [[ ${STATUS} == "ACTIVE" ]]; then
+              echo "Deploy successful"
+              echo ${OUTPUT}
+          else
+              echo "Deploy failed"
+              echo ${OUTPUT}
+              exit 1
+          fi
